---
- name: Check Status of Order Processing System
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Poll order system
    ansible.builtin.uri:
      url: http://44.203.123.10:8080/confirmation.html
