---
- name: Check Status of Order Processing System
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Poll order system
    ansible.builtin.uri:
      url: http://3.82.99.229:8080/confirmation.html
